### ISSUE TITLE
Don't assume arrays are string values

### ISSUE THREAD

**Issue by codecounselor** [rossmcdonald/telegraf#15]
There is a StatsD option `percentiles: [50,90,95,99]`

It seems like

```
{% if value is sequence and value is not string %}
    {{ key }} = [ "{{ value|join('", "') }}" ]
{% else %}
```

is causing the configuration to not allow an array of integers to be defined.

Or am I missing something?

**Comment by rossmcdonald** [comment]
Yes, currently sequences are (incorrectly) assumed to be string values. I'll update this to include some better logic in how the configuration is generated.

**Comment by codecounselor** [comment]
cool, thanks for the response.  Now that I've gotten some more experience with this role I had another question: would you accept a PR to do some checks that skip installation/restart/etc if nothing has in fact changed?

**Comment by rossmcdonald** [comment]
@codecounselor Absolutely. Please open a PR and cc me on it.
