### ISSUE TITLE
configure.yml failing with "AnsibleUndefinedVariable: 'dict object' has no attribute 'iteritems'"

### ISSUE THREAD

**Issue by sgreszcz** [rossmcdonald/telegraf#25]
Running this playbook to deploy Telegraf instances in several Ubuntu 16.04.2 LTS servers using ansible and python 3.6 on a Macbook. 

I had to put the full path to "src: /etc/ansible/roles/rossmcdonald.telegraf/templates/telegraf.conf.j2" in configure.yml to avoid errors but now I get this problem:

"AnsibleUndefinedVariable: 'dict object' has no attribute 'iteritems'"

And with the -vvvv traces, I get:

<cdc-sng-001> (0, b'\r\n\r\n{"stat": {"rgrp": true, "xusr": false, "exists": true, "block_size": 4096, "path": "/etc/telegraf/telegraf.conf", "isuid": false, "readable": true, "pw_name": "root", "wgrp": false, "attr_flags": "e", "rusr": true, "xgrp": false, "isreg": true, "woth": false, "blocks": 176, "uid": 0, "charset": "utf-8", "writeable": true, "mtime": 1499906354.0, "executable": false, "nlink": 1, "ischr": false, "wusr": true, "checksum": "e942793878aabb97aed9c8832c6ae669b112354c", "isblk": false, "version": "1977560557", "isdir": false, "mode": "0644", "roth": true, "issock": false, "atime": 1500324802.128394, "gr_name": "root", "inode": 405322, "attributes": ["extents"], "isgid": false, "xoth": false, "isfifo": false, "size": 86929, "mimetype": "text/plain", "dev": 64512, "device_type": 0, "ctime": 1500324801.868396, "islnk": false, "gid": 0}, "changed": false, "invocation": {"module_args": {"checksum_algorithm": "sha1", "checksum_algo": "sha1", "get_checksum": true, "follow": true, "get_md5": false, "path": "/etc/telegraf/telegraf.conf", "get_attributes": true, "get_mime": true}}}\r\n', b'Shared connection to cdc-sng-001 closed.\r\n')
fatal: [cdc-sng-001]: FAILED! => {
    "changed": false,
    "failed": true,
    "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'iteritems'"
}

**Comment by rossmcdonald** [comment]
Sorry, I just now saw this! It looks like you are using Python3, maybe? This role currently only supports Python2, but I'll look into support Python3 in the future as well.

**Comment by sgreszcz** [comment]
No problems, I am on Python3.  Got the deployment working by borrowing from several Telegraf recipes.  Cheers.

**Comment by samratBasra** [comment]
change your file src: /etc/ansible/roles/rossmcdonald.telegraf/templates/telegraf.conf.j2"
"iteritems" to "item" it will work.
