### ISSUE TITLE
Neo4j procstat plugin defaults

### ISSUE THREAD

**Issue by jrocketfingers** [rossmcdonald/telegraf#26]
I'm sorry to be so blunt, but why is there a neo4j procstat set in `defaults/main.yml`? Is this supposed to be your personal ansible role, or? I've reached it through https://github.com/influxdata/telegraf#ansible-role, so I unfairly assumed it should be as generic as possible.

How would I go about removing it without recreating the whole dictionary? As far as I understood it, I'm supposed to override only the `telegraf_plugins_extra` -- did I minsinterpret the intention?

Thanks, and once again, this is just an inquiry, I don't feel like I'm entitled to anything. I'll gladly fork and maintain my own flavor, I'm just looking for context.

**Comment by rossmcdonald** [comment]
The neo4j plugin is included in the defaults file as an example, and is supposed to be overridden depending on your personal needs. In fact, all of the `procstat` values are assumed to be overridden, as there are other extra entries there that probably won't be needed (there's also an `influxd`).

> How would I go about removing it without recreating the whole dictionary?

You should be recreating the whole dictionary. Everyone has different things they'd like Telegraf to collect, so it's up to you to figure out what those should be. The ones provided are simply there to serve as an example.

> As far as I understood it, I'm supposed to override only the telegraf_plugins_extra -- did I minsinterpret the intention?

The `telegraf_plugins_extra` variable is there in case you would like to set a base-set of inputs (CPU, memory, etc) and then add extras on a case-by-case basis (mongodb on a mongo instance, etc). These variables are there purely to help assist in those kinds of deployments, but you can only use base if that fits your use-case better. 

I agree that this is not well explained in the readme, so I apologize for the confusion. I'll add something there to make this more clear.

> Is this supposed to be your personal ansible role, or?

This was initially my personal ansible role, however others have found it helpful. You are more than welcome to fork and make it your own, or you can submit PR's if there are things you would like to contribute back.

Hope that helps!

**Comment by jrocketfingers** [comment]
All clear now, thanks, that helps a bunch!

I usually write roles without setting up defaults as examples since I want to catch errors explicitly (required variables defined in the readme), so it didn't really occur to me that could be just an example.

Sorry if I came out too offensive, it was definitely not my intention, but for the life of me, I couldn't think of a better way to ask. Bad day I guess :/
