### ISSUE TITLE
Default includes monitoring for neo4j

### ISSUE THREAD

**Issue by cptcanuck** [rossmcdonald/telegraf#37]
In defaults/main.yml
`  - name: procstat
    options:
      pid_file: "/var/lib/neo4j/data/neo4j-service.pid"
      prefix: "neo4j_proc"
`

I'm guessing this is a carryover from your local deployment, as it doesn't seem to be a standard part of a telegraf deployment. 

I'll submit a PR to remove that default, and if this isn't intentional you can use it, otherwise you can drop it :)

**Comment by rossmcdonald** [comment]
Fixed by #38
