### ISSUE TITLE
Updating Ansible Galaxy package

### ISSUE THREAD

**Issue by egegunes** [rossmcdonald/telegraf#42]
Can you update [Ansible Galaxy package](https://galaxy.ansible.com/rossmcdonald/telegraf)? Last version is 2 years old and there are 24 commits since then (including one of my own).

**Comment by rossmcdonald** [comment]
@egegunes Done, sorry about that. For some reason I thought it would automatically update by itself.

**Comment by filviu** [comment]
Resurecting to ask for another galaxy update :)

Unless you setup some automation it doesn't happen by itself 🤷 It's discussed here but I have yet to test it myself https://github.com/ansible/galaxy/issues/2070

**Comment by rossmcdonald** [comment]
@silviuvulcan Thanks for the reminder. I just cut a new 1.2.0 release as well as synced the latest with galaxy.

**Comment by filviu** [comment]
In case you are interested it's actually pretty simple. All I needed to do is add one action related file like this: 

https://github.com/silviuvulcan/ansible-role-activemq/blob/master/.github/workflows/release.yml and a repository secret with your ansible galaxy api key. 

Then when you push a new tag galaxy is notified automatically.
