### ISSUE TITLE
Set defaults vars like default telegraf conf ?

### ISSUE THREAD

**Issue by ahivert** [rossmcdonald/telegraf#6]
Is this normal to not have the same default vars as the default telegraf config ? 

I install manually telegraf **0.12.1** but :
##### Default plugins
- I don't have the input call **io** in your defaults but **diskio**. Maybe this is due to an update of telegraf ?
- I don't find in your defaults the input **kernel** but it's enabled with the default install of telegraf
###### cpu plugin

In your defaults, you have the option : 

``` yaml
drop:
      - cpu_time
```

but in the default install is :

``` yaml
fielddrop:
    - time_*
```
###### disk plugin

In your defaults, you have the option : 

``` yaml
mountpoints:
      - "/"
```

but in the default install **mountpoints** is commented and another is present :

``` yaml
ignore_fs:
    - tmpfs
    - devtmpfs
```
###### diskio or io plugin

In your defaults, you have the option : 

``` yaml
skip_serial_number: "true"
```

but in the default install all options are commented
###### kernel plugin

This plugin is not in your conf but enabled in telegraf conf

Maybe all of this it's a choice  ?

**Comment by amnay-mo** [comment]
This is no real issue. Just set them the way you want in your vars file.

**Comment by rossmcdonald** [comment]
I agree with @amnay-mo here. Telegraf's default configuration changes somewhat frequently, and I'd prefer that the defaults provide a good starting point for enabling/disabling your own plugins for your setup (not necessarily matching exactly what Telegraf provides as defaults).

I'm going to go ahead and close this, but let me know if you feel strongly about it and we can debate it further.
