### ISSUE TITLE
Failing for Ubuntu 22.04 (Jammy) and GH Actions proposal

### ISSUE THREAD

**Issue by filviu** [rossmcdonald/telegraf#60]
Hi,

Installing on Ubuntu 22.04 is failing because a "jammy" repo is not yet published. But apparently the repo structure is changing anyway and we should be using "stable" instead. 

https://community.influxdata.com/t/repo-for-ubuntu-jammy/24657/5

so repo should look like this:

```
https://repos.influxdata.com/ubuntu stable main
```

Weirder yet is that the doc site recomends using `/debian stable main` for both Ubuntu and Debian. And https://repos.influxdata.com/debian/dists/ seems to contain both Debian and Ubuntu releases. Anyways either should work. Would you like me to open a PR for this ?

Second question:

I've been using github actions to test various distros with my ansible-roles, would you be interested in a PR enabling such tests to allow detection of issues such as this ?

Cheers!

**Comment by rossmcdonald** [comment]
@filviu Sorry for the delay, but a PR for both/either would certainly be appreciated!

**Comment by filviu** [comment]
And sorry for the delay too :) apparently in the mean time a jammy repo has been published at 
```
deb https://repos.influxdata.com/ubuntu jammy stable
```

so I see no point in messing with the repos.
